project:
  type: book

execute:
  freeze: true

book:
  title: "RStudio Workbench Administration {{< var buildType >}} {{< var version >}}"
  subtitle: "{{< var buildType >}} Version {{< var version >}}"
  downloads: [docx, pdf]
  sharing: [twitter, facebook, linkedin]
  page-navigation: true
  site-url: https://pommevilla.github.io/incog-workbench
  repo-url: https://github.com/pommvilla/incog-workbench

  sidebar:
    collapse-level: 1
    style: "docked"
    align: "center"

  navbar:
    type: light
    search: true
    pinned: true
    logo: images/RStudio-ball.svg
    right:
      - text: "Rstudio.com"
        url: 'https://www.rstudio.com/'
      - text: "Release Notes"
        url: "https://support.rstudio.com/hc/en-us/articles/200716783-RStudio-Release-History"
      - text: "Help"
        url: "https://support.rstudio.com/hc/en-us"

  chapters:
    - part: "Getting Started"
      chapters:
        - text: "Introduction"
          file: index.qmd
        - getting_started/installation.qmd
        - getting_started/management_script.qmd
        - getting_started/accessing_the_server.qmd
        - text: "Support"
          file: getting_started/support.qmd
    - part: "Server Management"
      chapters:
        - server_management/server_management.qmd
        - server_management/core_administrative_tasks.qmd
        - server_management/logging.qmd
        - text: "Administrative Dashboard"
          file: server_management/administrative_dashboard.qmd
        - server_management/automated_crash_reporting.qmd
    - part: "Authenticating Users"
      chapters:
        - authenticating_users/authenticating_users.qmd
        - authenticating_users/customizing_signin.qmd
        - authenticating_users/user_provisioning.qmd
        - authenticating_users/restricting_access.qmd
        - authenticating_users/authorization_timeout.qmd
        - authenticating_users/pam_authentication.qmd
        - text: "SAML Single Sign-On (SSO) Authentication"
          file: authenticating_users/saml_sso.qmd
        - text: "OpenID Connect Authentication"
          file: authenticating_users/openid_connect_authentication.qmd
        - text: "Proxied Authentication"
          file: authenticating_users/proxied_authentication.qmd
        - text: "Google Accounts (deprecated)"
          file: authenticating_users/google_accounts.qmd
        - authenticating_users/authentication_migration.qmd
    - part: "Access and Security"
      chapters:
        - access_and_security/access_and_security.qmd
        - access_and_security/network_port_and_address.qmd
        - access_and_security/security_considerations.qmd
        - access_and_security/secure_sockets.qmd
        - access_and_security/cookies.qmd
        - access_and_security/server_permissions.qmd
        - access_and_security/running_with_a_proxy.qmd
    - part: "R Sessions"
      chapters:
        - r_sessions/r_sessions.qmd
        - r_sessions/r_executable_and_libraries.qmd
        - r_sessions/session_startup_scripts.qmd
        - text: "User and Group Profiles"
          file: r_sessions/user_and_group_profiles.qmd
        - text: "Multiple R Sessions"
          file: r_sessions/multiple_r_sessions.qmd
        - text: "PAM Sessions"
          file: r_sessions/pam_sessions.qmd
        - text: "Kerberos"
          file: r_sessions/kerberos.qmd
        - r_sessions/directory_management.qmd
        - r_sessions/workspace_management.qmd
        - r_sessions/first_project_template.qmd
        - text: "Project Sharing"
          file: r_sessions/project_sharing.qmd
        - r_sessions/package_installation.qmd
        - text: "Feature Limits"
          file: r_sessions/feature_limits.qmd
        - text: "Notifications"
          file: r_sessions/notifications.qmd
        - r_sessions/rstudio_connect_server.qmd
        - r_sessions/terminal_websockets.qmd
        - r_sessions/customizing_session_settings.qmd
    - part: "R Versions"
      chapters:
        - r_versions/r_versions.qmd
        - r_versions/installing_r.qmd
        - r_versions/configuring_default.qmd
        - r_versions/using_multiple_versions_of_r.qmd
        - r_versions/managing_upgrades.qmd
        - r_versions/session_initialization.qmd
    - part: "Load Balancing"
      chapters:
        - load_balancing/load_balancing.qmd
        - load_balancing/load_balancing_vs_job_launcher.qmd
        - load_balancing/configuration.qmd
        - load_balancing/access_and_availability.qmd
        - load_balancing/balancing_methods.qmd
    - part: "Auditing and Monitoring"
      chapters:
        - auditing_and_monitoring/auditing_and_monitoring.qmd
        - auditing_and_monitoring/auditing_configuration.qmd
        - auditing_and_monitoring/monitoring_configuration.qmd
        - auditing_and_monitoring/server_health_checks.qmd
    - part: "License Management"
      chapters:
        - license_management/license_management.qmd
        - license_management/license_activation_and_details.qmd
        - license_management/connectivity_requirements.qmd
        - license_management/evaluations.qmd
        - license_management/floating_licensing.qmd
        - license_management/userspace_licensing.qmd
    - part: "Data Connectivity"
      chapters:
        - data_connectivity/data_connectivity.qmd
        - data_connectivity/connectivity_using_odbc.qmd
        - data_connectivity/connectivity_using_r_packages.qmd
        - data_connectivity/snippet_files.qmd
    - part: "Job Launcher"
      chapters:
        - text: "Overview"
          file: job_launcher/job_launcher.qmd
        - job_launcher/configuration.qmd
        - job_launcher/running_the_launcher.qmd
        - job_launcher/load_balancing.qmd
        - job_launcher/creating_plugins.qmd
        - job_launcher/troubleshooting.qmd
    - part: "Tutorial API"
      chapters:
        - tutorial_api/tutorial_api.qmd
        - tutorial_api/configuration.qmd
        - tutorial_api/interface.qmd
        - tutorial_api/tutorial_api_methods.qmd
        - tutorial_api/tutorial_api_callbacks.qmd
    - part: "Jupyter Sessions"
      chapters:
        - jupyter_sessions/jupyter_sessions.qmd
        - jupyter_sessions/configuration.qmd
        - jupyter_sessions/troubleshooting.qmd
    - part: "VS Code Sessions"
      chapters:
        - vscode_sessions/vs_code_sessions.qmd
        - vscode_sessions/installation.qmd
        - vscode_sessions/configuration.qmd
        - vscode_sessions/multiple_sessions.qmd
        - vscode_sessions/troubleshooting.qmd
    - part: "Database"
      chapters:
        - database/database.qmd
        - database/configuration.qmd
        - database/migration.qmd
    - part: "Hardening"
      chapters:
        - hardening/hardening.qmd
        - text: "Set Up SSL"
          file: hardening/set_up_ssl.qmd
        - hardening/browser_security.qmd
        - hardening/r_session_security.qmd
        - hardening/database.qmd
        - hardening/other.qmd
        - hardening/example_secure_configuration.qmd
  appendices:
    - session_user_settings/session_user_settings.qmd
    - rstudio_ide_commands/rstudio_ide_commands.qmd
    - r_package_dependencies/r_package_dependencies.qmd
    - rstudio_server_cli/rstudio_server_cli.qmd
    - part: "RStudio Configuration"
      chapters:
        - rstudio_server_configuration/rstudio_server_configuration.qmd
        - rstudio_server_configuration/rserver_conf.qmd
        - rstudio_server_configuration/rsession_conf.qmd


number-depth: 2

format:
  html:
    theme:
      - cosmo
      - styles/styles.scss
    include-in-header: google_analytics.html
    number-sections: false

  pdf:
    toc: true

  docx:
    toc: true
